framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: query.bus
        buses:
            # command.bus:
            #     middleware:
            #         - validation
            #         - doctrine_transaction
            query.bus:
                middleware:
                    - validation
                    - 'App\Shared\QueryLoggerMiddleware' # Example of a middleware
            # event.bus:
            #     default_middleware: allow_no_handlers
            #     middleware:
            #         - validation
